# Generated by Django 3.2.8 on 2021-10-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_assignment',
            name='Submission_Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
